<a href="https://colab.research.google.com/github/khalidmahamud/pytorch_practise/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
torch.__version__

'2.5.0+cu121'

## Introduction to Tensors

### Creating tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
scalar.item()

7

In [7]:
scalar.dtype

torch.int64

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
vector.dtype

torch.int64

In [12]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX.dtype

torch.int64

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR.dtype

torch.int64

### Random tensors

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9439, 0.6048, 0.6523, 0.7723],
        [0.2028, 0.6333, 0.3379, 0.9120],
        [0.0588, 0.4478, 0.8777, 0.9930]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
random_tensor.dtype

torch.float32

In [24]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor

tensor([[[0.5831, 0.3041, 0.4457,  ..., 0.8121, 0.8810, 0.2646],
         [0.1510, 0.5364, 0.5379,  ..., 0.5418, 0.6415, 0.1632],
         [0.0735, 0.5861, 0.3940,  ..., 0.4415, 0.7507, 0.6265],
         ...,
         [0.0482, 0.2756, 0.6503,  ..., 0.1978, 0.2953, 0.8114],
         [0.5732, 0.7310, 0.7425,  ..., 0.2563, 0.3693, 0.8215],
         [0.3382, 0.1625, 0.1405,  ..., 0.2657, 0.7621, 0.8293]],

        [[0.5254, 0.6430, 0.9813,  ..., 0.1213, 0.3003, 0.5754],
         [0.3927, 0.2418, 0.7942,  ..., 0.8002, 0.9707, 0.2939],
         [0.0672, 0.1042, 0.6084,  ..., 0.0628, 0.7820, 0.8691],
         ...,
         [0.5480, 0.1761, 0.4405,  ..., 0.4932, 0.2290, 0.5151],
         [0.9305, 0.5744, 0.8395,  ..., 0.4540, 0.2871, 0.0195],
         [0.9848, 0.7794, 0.8810,  ..., 0.1369, 0.9350, 0.4399]],

        [[0.0793, 0.4876, 0.4814,  ..., 0.1732, 0.5183, 0.0556],
         [0.8866, 0.5709, 0.5729,  ..., 0.1296, 0.7803, 0.5853],
         [0.6459, 0.4202, 0.1946,  ..., 0.6337, 0.9070, 0.

In [25]:
random_image_size_tensor.ndim

3

In [26]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [27]:
random_image_size_tensor.dtype

torch.float32

### Zerors and ones

In [28]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros.dtype

torch.float32

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [32]:
# Creating tensor range
zero_to_ten = torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [34]:
# Default type [float32]
float_32_tensor = torch.tensor([1.0, 9.0, 7.0],
                       dtype=None,  # Datatype of the tensor (e.g. float32, float16, int32, etc.)
                       device=None, # Device of the tensor (e.g. cpu, cuda, mps, etc.)
                       requires_grad=False) # If gradients need to be computed for the Tensor
float_32_tensor

tensor([1., 9., 7.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
# float16 tensor or half-tensor
float_16_tensor = torch.tensor([1.0, 9.0, 7.0],
                             dtype=torch.float16)
# float_16_tensor = float_32_tensor.type(torch.float16)
# float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([1., 9., 7.], dtype=torch.float16)

## Getting information from tensor

In [37]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9035, 0.3284, 0.2900, 0.7485],
        [0.6974, 0.7733, 0.0353, 0.3925],
        [0.2946, 0.9529, 0.3037, 0.2075]])

In [38]:
# Get the datatype of the tensor
some_tensor.dtype

torch.float32

In [39]:
# Get the shape of the tensor
some_tensor.size(), some_tensor.shape   # Both does the same thing

(torch.Size([3, 4]), torch.Size([3, 4]))

In [40]:
# Get the device tensor is on
some_tensor.device

device(type='cpu')

## Manipulating tensors (tensor opeartions)

In [41]:
# Create a Tensor
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

In [42]:
# Additon
tensor1 + 10
# torch.add(tensor1, 10)

tensor([11, 12, 13])

In [43]:
# Subtraction
tensor1 - 10

tensor([-9, -8, -7])

In [44]:
# Multiplication
tensor1 * 10
# torch.mul(tensor1, 10)

tensor([10, 20, 30])

In [45]:
# Division
tensor1 / 10

tensor([0.1000, 0.2000, 0.3000])

In [46]:
# Transpose
some_tensor = torch.rand(2, 3)
some_tensor, some_tensor.T

(tensor([[0.1523, 0.1023, 0.1698],
         [0.1495, 0.0687, 0.9198]]),
 tensor([[0.1523, 0.1495],
         [0.1023, 0.0687],
         [0.1698, 0.9198]]))

In [47]:
# Matrix Multiplication
#1-dim
torch.matmul(tensor1, tensor2) # Output: Scalar

tensor(32)

In [48]:
# 2-dim
tensor3 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
tensor4 = torch.tensor([[4, 5],
                        [6, 7],
                        [8, 9]])

torch.matmul(tensor3, tensor4)  # Output: Matrix product (2x2 matrix)

tensor([[ 40,  46],
        [ 94, 109]])

In [49]:
torch.matmul(torch.tensor([1, 2, 3]), torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

tensor([30, 36, 42])

In [50]:
torch.matmul(torch.tensor([[1, 2], [3, 4]]), torch.tensor([5, 6]))

tensor([17, 39])

## Finding tensor aggregations (mean, sum, min, max, etc.)

In [51]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.dtype

torch.int64

In [53]:
torch.min(x)  # min

tensor(0)

In [54]:
torch.max(x)  # max

tensor(90)

In [55]:
torch.mean(x) # mean

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [56]:
torch.mean(x.type(torch.float32)) # mean

tensor(45.)

In [57]:
torch.sum(x)  # sum

tensor(450)

## Finding positional min and max

In [58]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
x.argmin()   # index of min

tensor(0)

In [60]:
x.argmax()  # index of max

tensor(9)

## Reshaping, Stacking, Squeezing, and Unsqueezing

In [61]:
tensor = torch.arange(1., 10.)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [63]:
# Reshaping - reshapes and input tensor to a defined shape

tensor_reshaped = tensor.reshape(9, 1)
tensor_reshaped, tensor_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [64]:
tensor_reshaped = tensor.reshape(3, 3)
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [74]:
# View - return a view of an input tensor of certain shape but keep the same memory as the original tensor.
# Changing the view of a tensor changes the original tensor becauase view of a tensor shares the same memory as the original input.

tensor_view = tensor.view(1, 9)
tensor_view, tensor_view.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
tensor_view[:, 0] = 5
tensor, tensor_view

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [79]:
tensor[0] = 1
tensor, tensor_view

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [82]:
# Stacking - combine multiple tensors on top of each other (dim = 0) or side by side (dim = 1)

tensor_stacked = torch.stack([tensor, tensor, tensor], dim=0)
tensor_stacked, tensor_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([3, 9]))

In [83]:
tensor_stacked = torch.stack([tensor, tensor, tensor], dim=1)
tensor_stacked, tensor_stacked.shape

(tensor([[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]),
 torch.Size([9, 3]))

In [88]:
# Squeeze - removes all 1 dimensions from a tensor

tensor_reshaped = tensor.reshape(1, 9)
tensor_squeezed = torch.squeeze(tensor)
tensor_reshaped, tensor_reshaped.shape, tensor_squeezed, tensor_squeezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [92]:
# Unsqueeze - add a 1 dimension to a target tensor
tensor_unsqueezed = torch.unsqueeze(tensor_squeezed, dim=0)
tensor_unsqueezed, tensor_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [93]:
tensor_unsqueezed = torch.unsqueeze(tensor_squeezed, dim=1)
tensor_unsqueezed, tensor_unsqueezed.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [97]:
# Permute - return a view of the input with dimensions permuted (swapped) in a certain way
# Rearrange the dimensions of a target tensor in a specified order

tensor_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
tensor_permuted = tensor_original.permute(2, 0, 1) # [color_channels, height, width]
tensor_original.shape, tensor_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [100]:
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [101]:
torch.permute(tensor_reshaped, dims=(1, 0)), torch.permute(tensor_reshaped, dims=(1, 0)).shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))