<a href="https://colab.research.google.com/github/khalidmahamud/pytorch_practise/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
torch.__version__

'2.4.1+cu121'

## Introduction to Tensors

### Creating tensors

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [12]:
scalar.shape

torch.Size([])

In [7]:
scalar.item()

7

In [31]:
scalar.dtype

torch.int64

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [32]:
vector.dtype

torch.int64

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [33]:
MATRIX.dtype

torch.int64

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [34]:
TENSOR.dtype

torch.int64

### Random tensors

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7505, 0.7836, 0.2536, 0.8687],
        [0.0919, 0.7291, 0.3222, 0.3221],
        [0.7084, 0.2182, 0.0611, 0.6021]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [35]:
random_tensor.dtype

torch.float32

In [25]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor

tensor([[[7.0121e-01, 3.3523e-01, 4.9178e-01,  ..., 1.4107e-01,
          7.9058e-01, 8.6642e-01],
         [2.0838e-01, 2.9431e-01, 7.6582e-01,  ..., 8.7513e-01,
          9.8658e-01, 8.1246e-01],
         [3.6471e-01, 6.5271e-01, 9.2665e-01,  ..., 2.7115e-01,
          6.4003e-01, 5.3608e-01],
         ...,
         [4.1607e-01, 2.8974e-04, 4.8224e-01,  ..., 9.5057e-01,
          8.6783e-02, 7.1751e-01],
         [9.6560e-01, 6.7288e-01, 4.5351e-01,  ..., 7.3928e-01,
          8.9478e-01, 5.8202e-01],
         [3.0004e-01, 4.0263e-01, 3.3643e-01,  ..., 6.6275e-01,
          1.8900e-01, 1.7980e-02]],

        [[6.1706e-01, 1.4403e-01, 1.1605e-04,  ..., 5.9137e-01,
          7.5424e-02, 9.2234e-02],
         [8.1197e-01, 9.2922e-01, 7.9931e-01,  ..., 4.2429e-01,
          7.2391e-01, 7.1956e-01],
         [1.2726e-01, 7.1655e-01, 3.4674e-01,  ..., 4.7135e-02,
          7.2262e-01, 5.9235e-01],
         ...,
         [1.2503e-01, 7.9296e-02, 9.9524e-02,  ..., 7.3470e-01,
          7.166

In [26]:
random_image_size_tensor.ndim

3

In [27]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [37]:
random_image_size_tensor.dtype

torch.float32

### Zerors and ones

In [29]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
zeros.dtype

torch.float32

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
ones.dtype

torch.float32