<a href="https://colab.research.google.com/github/khalidmahamud/pytorch_practise/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

In [12]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
torch.__version__

'2.4.1+cu121'

## Introduction to Tensors

### Creating tensors

In [14]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
scalar.ndim

0

In [16]:
scalar.shape

torch.Size([])

In [17]:
scalar.item()

7

In [18]:
scalar.dtype

torch.int64

In [19]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [20]:
vector.ndim

1

In [21]:
vector.shape

torch.Size([2])

In [22]:
vector.dtype

torch.int64

In [23]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
MATRIX.ndim

2

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
MATRIX.dtype

torch.int64

In [27]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [28]:
TENSOR.ndim

3

In [29]:
TENSOR.shape

torch.Size([1, 3, 3])

In [30]:
TENSOR.dtype

torch.int64

### Random tensors

In [31]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5517, 0.6979, 0.6342, 0.6807],
        [0.5376, 0.1776, 0.1774, 0.0575],
        [0.1846, 0.4384, 0.5221, 0.0820]])

In [32]:
random_tensor.ndim

2

In [33]:
random_tensor.shape

torch.Size([3, 4])

In [34]:
random_tensor.dtype

torch.float32

In [35]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor

tensor([[[0.3920, 0.9922, 0.2793,  ..., 0.3261, 0.1941, 0.6776],
         [0.1937, 0.7906, 0.6545,  ..., 0.5777, 0.7067, 0.5852],
         [0.0698, 0.5302, 0.9493,  ..., 0.2658, 0.5251, 0.3414],
         ...,
         [0.9217, 0.9857, 0.8945,  ..., 0.0307, 0.3920, 0.6350],
         [0.9162, 0.9953, 0.1240,  ..., 0.5876, 0.8444, 0.3513],
         [0.8520, 0.0459, 0.8022,  ..., 0.8117, 0.5316, 0.1849]],

        [[0.0844, 0.9037, 0.4128,  ..., 0.1896, 0.8933, 0.9665],
         [0.4894, 0.2815, 0.5202,  ..., 0.8083, 0.5443, 0.8210],
         [0.3122, 0.2756, 0.9029,  ..., 0.7404, 0.6525, 0.9981],
         ...,
         [0.2754, 0.5581, 0.4933,  ..., 0.8648, 0.4082, 0.4320],
         [0.4445, 0.1691, 0.4320,  ..., 0.0788, 0.4983, 0.7209],
         [0.0471, 0.7126, 0.8648,  ..., 0.0658, 0.7319, 0.1875]],

        [[0.9986, 0.7720, 0.2897,  ..., 0.6070, 0.5502, 0.6630],
         [0.7059, 0.2993, 0.5008,  ..., 0.9238, 0.0944, 0.7247],
         [0.2943, 0.7074, 0.7442,  ..., 0.6895, 0.4970, 0.

In [36]:
random_image_size_tensor.ndim

3

In [37]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [38]:
random_image_size_tensor.dtype

torch.float32

### Zerors and ones

In [39]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
zeros.dtype

torch.float32

In [41]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [42]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [43]:
# Creating tensor range
zero_to_ten = torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [53]:
# Default type
float_32_tensor = torch.tensor([1.0, 9.0, 7.0],
                       dtype=None,  # Datatype of the tensor (e.g. float32, float16, int32, etc.)
                       device=None, # Device of the tensor (e.g. cpu, cuda, mps, etc.)
                       requires_grad=False) # If gradients need to be computed for the Tensor
float_32_tensor

tensor([1., 9., 7.])

In [54]:
float_32_tensor.dtype

torch.float32

In [55]:
# float16 tensor or half-tensor
float_16_tensor = torch.tensor([1.0, 9.0, 7.0],
                             dtype=torch.float16)
# float_16_tensor = float_32_tensor.type(torch.float16)
# float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([1., 9., 7.], dtype=torch.float16)

In [56]:
float_16_tensor.dtype

torch.float16